Repository DasNasu/Fiae-DE, pull requests merged in 2022-03, with the labels that each got.

#100 Closes #99
  backend/DatabaseManager.php
  classes/Category.php
  classes/MenuItem.php
  classes/Navigation.php
  index.php
  pages/Home.php
  pages/get.php
Labels: pull requested

#101 database updates and css fixes
  backend/DatabaseManager.php
  classes/Category.php
  classes/MenuItem.php
  classes/Navigation.php
  index.php
  pages/Home.php
  templates/style/global.scss
Labels: enhancement, pull requested

#102 hotfix
  pages/Downloads.php
  pages/get.php
Labels: bug, pull requested

#103 hotfix
  pages/Downloads.php
  pages/get.php
Labels: bug, pull requested

#110 Fixes #109
  pages/Upload.php
Labels: pull requested

#111 Update release branch
  pages/Upload.php
Labels: pull requested

#126 Closes #45, #112, #113
  backend/DatabaseManager.php
  classes/Helpers.php
  classes/User.php
  pages/Admin.php
  pages/Home.php
  pages/Login.php
  pages/admin/Category.php
  pages/admin/permissionDenied.html
  pages/get.php
  templates/style/global.scss
Labels: pull requested

#105 Improved layout (#104)
  templates/style/global.scss
Labels: enhancement

#106 Fixed header dropdown and foot er (#85)
  templates/style/global.scss
Labels: enhancement

#127 Creating Imprint
  pages/Imprint.html
Labels: pull requested, documentation

#128 Closes #124
  pages/Dataprotection.html
Labels: pull requested, documentation

#130 minor bugfixes
  backend/DatabaseManager.php
  classes/Category.php
  index.php
Labels: bug, pull requested
